// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig,env } from "prisma/config";
import "dotenv/config"
console.log(process.env.DATABASE_URL);

export default defineConfig({
  schema: "./src/prisma/schema.prisma",
  migrations: {
    path: "./src/prisma/migrations",
    seed:"./src/prisma/seed.js",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
